blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Discussions
    url: https://github.com/space-code/typhoon/discussions
    about: Ask questions and discuss ideas with the community
  - name: ðŸ“š Documentation
    url: https://github.com/space-code/typhoon
    about: Read the documentation